apiVersion: v1
kind: PersistentVolume
metadata:
  name: esconfig-pv
spec:
  storageClassName: esconfig
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes/pv/esconfig-pv"
