apiVersion: v1
kind: PersistentVolume
metadata:
  name: esdata-pv
spec:
  storageClassName: esdata
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubernetes/pv/esdata-pv"
