apiVersion: v1
kind: PersistentVolume
metadata:
  name: esdata-pv
spec:
  storageClassName: nfs
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 172.16.1.52
    path: /mnt/array1/dump
