ingress:
  enabled: false

elasticsearch:
  image:
    repository: elasticsearch
    tag: "7.3.1"
    pullPolicy: IfNotPresent
  memory: 32g
  persistence:
    data:
      size: 200Gi
      storageClassName: rook-ceph-block-retain

fluentd:
  image:
    # repository: wide-camp-1909/unbound-efk-fluentd
    repository: 203.178.158.5:30500/wide-camp-1909/unbound-efk-fluentd
    tag: "latest"
    pullPolicy: IfNotPresent
  listen: 203.178.158.40

kibana:
  image:
    repository: kibana
    tag: "7.3.1"
    pullPolicy: IfNotPresent
  listen: 203.178.158.41
