ingress:
  enabled: false

elasticsearch:
  image:
    repository: elasticsearch
    tag: "7.3.1"
  pullPolicy: IfNotPresent
  persistence:
    data:
      size: 20Gi
      storageClassName: es
    config:
      size: 2Gi
      storageClassName: es

fluentd:
  image:
    repository: wide-camp-1909/ubuntu-efk-fluentd
    tag: "latest"
  pullPolicy: IfNotPresent

kibana:
  image:
    repository: kibana
    tag: "7.3.1"
  pullPolicy: IfNotPresent
