version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.3.1
    expose:
      - 9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      indices.query.bool.max_clause_count: 8192
      search.max_buckets: 100000
      action.destructive_requires_name: "true"
      network.host: 0.0.0.0
      http.port: 9200
    ulimits:
      memlock:
        soft: -1
        hard: -1

  fluentd:
    image: wide-camp-1909/unbound-efk-fluentd:latest
    build:
      context: fluentd
    ports:
      - "514:5140/udp"
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf:ro

  kibana:
    image: kibana:7.3.1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      SERVER_MAXPAYLOADBYTES: 4194304
      LOGGING_DEST: stdout
      LOGGING_QUIET: "false"
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 5601
    depends_on:
      - elasticsearch

volumes:
  esdata:
  esconfig:
