apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-kibana-deployment
  labels:
{{ include "unbound-efk.labels" . | indent 4 }}
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-08-31T23:23:03Z"
  generation: 1
spec:
  replicas: {{ .Values.unbound.replicaCountMin }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kibana
{{ include "unbound-efk.labels" . | indent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
{{ include "unbound-efk.labels" . | indent 8 }}
    spec:
      containers:
        - name: unbound
          image: {{ .Values.kibana.image.repository }}:{{ .Values.kibanna.image.tag }}
          imagePullPolicy: {{ .Values.kibana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5601
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 5601
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: "/"
              port: 5601
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 1
