apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-elasticsearch
  labels:
{{ include "unbound-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
{{ include "unbound-efk.labels" . | indent 4 }}
  ports:
    - name: elasticsearch
      targetPort: 9200
      port: 9200
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fluentd
  labels:
{{ include "unbound-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: fluentd
{{ include "unbound-efk.labels" . | indent 4 }}
  ports:
    - name: syslog
      targetPort: 5140
      port: 514
      protocol: UDP
  externalIPs:
    - {{ .Values.fluentd.listen }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kibana
  labels:
{{ include "unbound-efk.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: kibana
{{ include "unbound-efk.labels" . | indent 4 }}
  ports:
    - name: http
      targetPort: 5601
      port: 5601
      protocol: TCP
  externalIPs:
    - {{ .Values.kibana.listen }}
