apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
{{ include "camp-dns.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app: unbound
{{ include "camp-dns.labels" . | indent 4 }}
  ports:
    - name: dns-udp
      targetPort: 53
      port: 53
      protocol: UDP
    - name: dns-tcp
      targetPort: 53
      port: 53
      protocol: TCP
  externalIPs:
{{ range .Values.unbound.listen }}
    - {{ . }}
{{ end }}
